### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mobile-desk** [PeterHdd/Firebase-Flutter-tutorials#1]
error: The expression doesn't evaluate to a function, so it can't be invoked. (invocation_of_non_function_expression at [koude] lib\main.dart:39)

**Comment by PeterHdd** [comment]
on which line are u getting this error?

The firebase plugins got a breaking change update recently, and since I think your question is related to the plugin updates, then check my answers here to see how to fix the errors:

https://stackoverflow.com/questions/63597313/the-argument-type-mapstring-dynamic-function-cant-be-assigned-to-the-par/63597596#63597596

https://stackoverflow.com/questions/63529174/the-operator-isnt-defined-error-when-using-data-in-flutter-firestore/63529675#63529675

https://stackoverflow.com/questions/63492211/no-firebase-app-default-has-been-created-call-firebase-initializeapp-in/63492262#63492262

https://stackoverflow.com/questions/63486340/cloud-firestore-0-14-0-how-to-use-the-data-method/63486506#63486506

https://stackoverflow.com/questions/63482162/undefined-class-firebaseuser/63482356#63482356

**Comment by mobile-desk** [comment]
Main.dart

Around the place you introduced res.


My laptop is off so i cant check it now

**Comment by ghost** [comment]
Why not edit it on your git hub

**Comment by PeterHdd** [comment]
@samothmailiw  Yes that's because the `currentUser` is not a function anymore and its a property now:

https://stackoverflow.com/questions/63482162/undefined-class-firebaseuser/63482356#63482356

**Comment by PeterHdd** [comment]
Hi @praisecobasi ,

The reason I didn't update on GitHub yet, is because I was passing through a rough time personally and I didn't have time to do a full update for the articles and the repository. But I will do that soon. For now, you can check the urls provided above since they pretty much solve all the issues with the new plugin updates.

**Comment by PeterHdd** [comment]
all updated
